function [dU,dUm1,dT,dTm1,Div,Div1, T, U] = PSA(FilePathName)
       %Zero all variables in case of repeated PSA
        dU = 0;
        dT = 0;
        dUm1 = 0;
        dTm1 = 0;
        Div = 0;
        Div1 = 0;
        T = 0;
        U = 0;
        Uf = 0;
        n = 0;
        
        %Import the voltage file (assumed mV following discussion during
        %lecture on 06/05/2014)
        U = importdata(FilePathName);
        %Evenly distribute the time - we know it is 1 second
        T = transpose(linspace(0,1,length(U)));
        
        % --- Filtering
        %Extend U to next power of two length for wavelet transform
        n = 524288 - length(U);
        Uf = wextend(1, 'sym', U, n, 'r');
        %Use function generated by tool
        Uf = func_denoise_sw1d(Uf);
        %Unextend it and free up memory
        n = length(U);
        U = Uf(1:n);
        Uf = 0;
        
        %Filter the Variables to find the PD peaks
        PD_Threshold = 0.3;
        T = T(abs(U)>PD_Threshold);
        U = U(abs(U)>PD_Threshold);
        
        %Preallocate variable lengths for speed
        dU = zeros(length(U),1);
        dT = zeros(length(U),1);
        %dU(n) = U(n+1) - U(n)
        %dT(n) = T(n+1) - T(n)
        %Generate the delta variables
        for i = 1:(length(U)-1)
            dU(i) = U(i+1)-U(i);
            dT(i) = T(i+1)-T(i);
        end
        
        %Preallocate variable length for speed
        dUm1 = zeros(length(U)+1,1);
        dTm1 = zeros(length(U)+1,1);
        %dU(n-1) = U(n) - U(n-1)
        %Generate the -1 variables
        for i = 2:length(U) %start at 2 as U0 is not an index
            dUm1(i) = U(i) - U(i-1);
            dTm1(i) = T(i) - T(i-1);
        end
        
        %Delete index 1 of minus ones as they are unasigned
        dUm1(1) = [];
        dTm1(1) = [];
        %Also need to delete ends to make same length vectors
        dUm1(length(dUm1)) = [];
        dTm1(length(dTm1)) = [];
        %Delete vector 1 of the n values to keep offset
        dU(1) = [];
        dT(1) = [];
        
        %preallocate array length for speed
        Div = zeros(length(dU),1);
        Div1 = zeros(length(dU),1);
        %Calculate the divided values
        for i = 1:length(dU)
            Div(i) = dU(i)/dT(i);
            Div1(i) = dUm1(i)/dTm1(i);
        end
        
    end